email: your-email@example.com
description: > 
  Flyve MDM Agent for Android
baseurl: "/flyve-mdm-android-inventory-agent"
url: "https://flyve-mdm.github.io"

# Build settings
markdown: kramdown

plugins:
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-sitemap

repository: flyve-mdm/flyve-mdm-android-inventory-agent

sass:
    style: compressed

prose:

  ignore: 
    - .gitignore 
    - _config.yml
    - Gemfile
    - Gemfile.lock
    - _layouts
    - _includes
    - fonts
    - css
    - images
    - js
    - apple-touch-icon.png
    - CHANGELOG.md
    - 404.html
    - index.html
    - manifest.json
    - news.html
    - sw.js
    - products.html
    - assets

  media: "images"

  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: false
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
